### ISSUE TITLE
Warning: Frame scripts cannot be added to empty keyframes.

### ISSUE THREAD

**Issue by kburke3** [jiborobot/pixi-animate#62]
Hi,
I'm using this.stop() from my timeline in an empty layer. I get an error on export from Adobe Animate:
`Warning: Frame scripts cannot be added to empty keyframes. (Layer: 0)`

From a desktop web browser, the this.stop() calls work. When I load my Pixi Animate animation in an Android Web View, however, the this.stop() calls are ignored. What would be the best practice for adding a script to a MovieClip?

To prevent the MovieClips from reseting to the first frame upon completion, I added the following. It still does not allow me to stop the timeline from the MovieClip's timeline.

```javascript
mc.autoReset = false;
```

Any help would be tremendous. Thanks!

**Comment by bigtimebuddy** [comment]
Yes, you cannot add frame scripts on empty keyframes. It's a limitation of the SDK for Adobe Animate, these frame scripts are ignored. You need to add something on the frame, even if it's an invisible graphic.

Try `console.log` in your frame script to see if it's being called. PixiAnimate by default drops frames on lower performing devices, which might be causing the frame to be skipped. I'm working on a new major release which will make frame-dropping opt-in instead of automatically used.

As a workaround, I'd strongly suggest you use `PIXI.animate.Animator` API http://jiborobot.github.io/pixi-animate/PIXI.animate.Animator.html

This will allow you to play sequences of your animation by spanning between frame numbers or frame labels. Much easier to control your choreography this way than frame labels.
